# Minifolio
# Example docker-compose.yml
#
# Usage:
# * The data directory will be set up inside `./data` on the host system
# * You should create a `.env` file to contain the `AUTH_SECRET` environment
#   variable. Perhaps you could generate this using the command here:
#   https://unix.stackexchange.com/a/476125/161355
#
# It is not necessary to set up other environment variables
services:
  minifolio:
    image: maddyguthridge/minifolio
    hostname: minifolio
    restart: always
    ports:
      - 127.0.0.1:5010:3000/tcp
    volumes:
      - "./data:/data:rw"
        # Forward local machine SSH key to docker
        # Note: this may need changes on MacOS
        # Source: https://stackoverflow.com/a/36648428/6335363
      - ${SSH_AUTH_SOCK:-$XDG_RUNTIME_DIR/ssh-agent.socket}:/ssh-agent
      - "ssh_dir:/home/node/.ssh:rw"
    environment:
      DATA_REPO_PATH: "/data"
      HOST: 0.0.0.0
      PORT: 3000
      # Tell the container where to find the SSH auth socket
      SSH_AUTH_SOCK: /ssh-agent
    # Set up `AUTH_SECRET` variable within `.env`
    env_file: ".env"
volumes:
  ssh_dir:
