containers:
  bedrock:
    # Backup the world "mcbedrock@ursula" on the "public" docker container
    - name: public
      # Tells the backup service that this container is accessible
      # using the mc-server-runner SSH functionality.
      # passwordFile should point to the .remote-console.yaml file in the container
      ssh: public:2222
      passwordFile: /bedrock/.remote-console.yaml
      worlds:
        - "/bedrock/worlds/mcbedrock@ursula"
schedule:
  # This will perform a backup every day.
  interval: 1d
trim:
  # Keep all backups for the last 7 days
  # Keep at least one backup for the last month
  # Keep at least two backups per world
  trimDays: 7
  keepDays: 31
  minKeep: 2
