# Jellyfin
# Adapted from https://jellyfin.org/docs/general/installation/container
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    # user: uid:gid
    ports:
      - 8096:8096/tcp
      - 7359:7359/udp
    volumes:
      - ./config:/config
      - ./cache:/cache
      - type: bind
        source: /mnt/maddyflix
        target: /media
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    environment:
      JELLYFIN_PublishedServerUrl: 'internal=http://192.168.1.112:8096, external=https://jellyfin.maddyguthridge.com'
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - 'host.docker.internal:host-gateway'
