services:
  backup:
    image: kaiede/minecraft-bedrock-backup
    restart: always
    container_name: bedrock_backup
    # Make sure the minecraft images start before the backup
    depends_on:
      public:
        condition: service_healthy
    environment:
        # Useful for making sure your logs have a proper timestamp
        TZ: "Australia/Sydney"
    volumes:
      # (Optional) Map a configuration folder separately from the backups
      - "./config:/config"
      # Map your backups folder info /backups
      - "/mnt/nextcloud-backup/minecraft:/data:rw"
      # Map the data folders for the server
      - "/opt/bedrock/public:/bedrock"

  public:
    image: itzg/minecraft-bedrock-server
    restart: always
    container_name: bedrock_public
    # Expose the mc-server-runner's SSH port to just the backup container
    expose:
      - 2222
    # Make the minecraft server ports public
    ports:
      - 19132:19132/udp  # Gameplay + LAN discovery
      - 19133:19133/udp  # Gameplay
    environment:
      # Set target version
      VERSION: "LATEST"
      # Enable SSH
      ENABLE_SSH: "TRUE"
      # Server settings
      EULA: "TRUE"
      # Timezone
      TZ: "Australia/Sydney"
      # Server properties
      SERVER_NAME: "Onyxx Land"
      LEVEL_NAME: "mcbedrock@ursula"
      LEVEL_SEED: "-6779976332610208683"
      GAMEMODE: "survival"
      DIFFICULTY: "hard"
      ONLINE_MODE: "false"
      PLAYER_IDLE_TIMEOUT: "120"
      VIEW_DISTANCE: "32"
      TICK_DISTANCE: "4"
    volumes:
      - /opt/bedrock/public:/data
    stdin_open: true
    tty: true
